from api.database.config.entity_base import Base
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import DateTime, ForeignKey, Integer, LargeBinary, String, Text
from datetime import datetime

class BoardEntity(Base):
    __tablename__ = "board"
    bno: Mapped[int] = mapped_column("bno", Integer, primary_key=True, autoincrement=True)
    btitle: Mapped[str] = mapped_column("btitle", String(255))
    bcontent: Mapped[str | None] = mapped_column("bcontent", Text)
    bwriter: Mapped[str] = mapped_column("bwriter", String(50), ForeignKey("member.mid"))
    bdate: Mapped[datetime] = mapped_column("bdate", DateTime())
    bhitcount: Mapped[int] = mapped_column("bhitcount", Integer, server_default="0")
    battachoname: Mapped[str | None] = mapped_column("battachoname", String(255))
    battachsname: Mapped[str | None] = mapped_column("battachsname", String(255))
    battachtype: Mapped[str | None] = mapped_column("battachtype", String(255))
    battachdata: Mapped[bytes | None] = mapped_column("battachdata", LargeBinary)
    
"""
SQLAlchemy가 자동 생성하는 DDL

=== Oracle 12c 이상 ===
CREATE TABLE board (
    bno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    btitle VARCHAR2(255) NOT NULL,
    bcontent CLOB,
    bwriter VARCHAR2(50) NOT NULL REFERENCES member(mid),
    bdate TIMESTAMP NOT NULL,
    bhitcount NUMBER DEFAULT 0 NOT NULL,
    battachoname VARCHAR2(255),
    battachsname VARCHAR2(255),
    battachtype VARCHAR2(255),
    battachdata BLOB
);

=== PostgreSQL ===
CREATE TABLE board (
    bno SERIAL NOT NULL PRIMARY KEY,
    btitle VARCHAR(255) NOT NULL,
    bcontent TEXT,
    bwriter VARCHAR(50) NOT NULL REFERENCES member (mid),
    bdate TIMESTAMP NOT NULL,
    bhitcount INTEGER DEFAULT 0 NOT NULL,
    battachoname VARCHAR(255),
    battachsname VARCHAR(255),
    battachtype VARCHAR(255),
    battachdata BYTEA
);

주의사항:
- default=0, default=lambda 등은 Python 레벨 기본값으로 DDL에 DEFAULT 절이 생성되지 않음
- server_default="0" 형태로 지정해야 DDL에 DEFAULT 절이 포함됨
- Oracle: GENERATED BY DEFAULT AS IDENTITY는 12c 이상에서 지원
- PostgreSQL: SERIAL은 INTEGER + SEQUENCE를 자동 생성하는 특수 타입
"""